### ISSUE TITLE
Channel_packer doesn't handle display_scale properly

### ISSUE THREAD

**Issue by zedrun00** [TokisanGames/Terrain3D#531]
### Terrain3D version

master

### System information

v4.4

### Is the issue reproducable in the demo?

Yes

### Issue description

in display_scale = 100%, normal, other scale have bug

![`V05_8ZDI`PN8BHVT10{~18](https://github.com/user-attachments/assets/f1242814-9192-4baf-b506-5464ddf18097)
![%UZZJA CE$RZ9Z9(14 G A8](https://github.com/user-attachments/assets/0d3c6afe-0277-4dfe-9856-6c6b8e96b6d4)
![_ A207G8{1TX7 LEAYDU $U](https://github.com/user-attachments/assets/0e728e7b-a058-40a5-99ff-d7b32647dffd)

### Logs

none

**Comment by TokisanGames** [comment]
I don't intend to look at 4.4 until the release candidates since it's full of bugs. It's unsupported until then.

**Comment by zedrun00** [comment]
@TokisanGames 
look this in 4.3
![image](https://github.com/user-attachments/assets/33b78ae2-1f40-4830-a45a-95ad4f216782)

**Comment by TokisanGames** [comment]
Fixed by #541. You can use a nighty build of either 1.0 (main) or 0.9.3 https://terrain3d.readthedocs.io/en/latest/docs/nightly_builds.html

**Comment by cclawhon** [comment]
1. Sorry I duplicated request in #601 :-/ 
2. Sadly: Not fixed...tried 1. nightly, 2. assetlib, 3. latest zip, and none had popup fixed, 
3. also unable to load normal jpg without freeze. 
4. Went through and ensured all display scales were 100%--didn't fix. Changed window size to different resolutions, tried "canvas items", no luck. 
5. On the Latest Zip: I had to bypass security on the Mac_os debug lib and one other file I can't remember now to make errors stop (control click, open with text edit, then close text edit, then control-click open again and say open anyways 
6. Once in, reloaded project. 
7. On Run main demo project (one with the wall) in latest zip, whole computer crashed. I can't risk that so have to stop testing and remove all files. Sorry :-/ Used to love Terrain3d before my M1 Max tho! Amazing work you all!

**Comment by TokisanGames** [comment]
> Sadly: Not fixed...tried 1. nightly, 2. assetlib, 3. latest zip, and none had popup fixed, 

The display scale is fixed in the nightly builds, only. If you don't see it changing, then we can help you with the correct upgrade process. 

> I had to bypass security on the Mac_os debug lib 

That is expected with unsigned builds, unless you build it yourself. 

> On Run main demo project (one with the wall) in latest zip, whole computer crashed. I can't risk that so have to stop testing and remove all files.

As user space apps, neither Terrain3D, nor Godot can crash your computer. Your kernel won't allow it. We can only crash Godot. The only thing that can crash your computer is the kernel or anything that runs in kernel space, like video card drivers, which is undoubtedly the cause. As a user space app, Godot can ask your video card driver to do something that triggers a bug in the driver and cause a crash. The solution is to upgrade your driver or your kernel, or both. 

Someone on our discord had a similar problem with macos and I told them the same thing. They reported, "So after pondering your guidance on my crash, I upgraded my Mac OS to Sequoia from Sonoma and launched your demo again...It runs!!!  Thank you for your direction. I can now work with your plugin!"
